baseURL = 'https://www.yojnaportal.com'
languageCode = 'en-us'
title = 'YOJNA PORTAL'
theme = 'my-theme'

# Add taxonomies
[taxonomies]
  category = "categories"
[params]
  defaultContentType = "page"
description = "Stay updated with the latest government schemes, Sarkari Yojna news, and policy updates on Yojna Portal."


  
# config.toml

googleAnalytics = "G-GWSRPE5DVE"


[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1
[outputs]
home = ["HTML", "JSON"]


[sitemap]
  filename = "sitemap.xml"
  changefreq = "daily"
  priority = 0.5
 