name: Auto Update Hugo Site

on:
  schedule:
    - cron: '0 0 * * *' # हर रात 12 बजे

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'

    - name: Build Hugo site
      run: hugo

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
